# Generated by Django 2.2.9 on 2020-01-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='criado em'),
        ),
    ]
