# Generated by Django 2.2.9 on 2020-01-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200122_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='email',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
